# Generated by Django 3.2 on 2021-04-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cep',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.PositiveBigIntegerField(),
        ),
    ]
