# Generated by Django 3.2 on 2021-04-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Completo'), ('AP', 'Aguardando Pagamento'), ('P', 'Processando'), ('E', 'Enviado'), ('CN', 'Cancelado')], max_length=2),
        ),
    ]
