# Generated by Django 3.2 on 2021-04-17 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0451bdae-71f8-4594-8323-cff189ba9e1a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
